server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics
  health:
    mongo:
      enabled: true
spring:
  data:
    mongodb:
      database: nhais
      uri: mongodb://localhost:27017
nhais:
  amqp:
    brokers:
    meshOutboundQueueName: nhais_mesh_outbound
    meshInboundQueueName: nhais_mesh_inbound
    gpSystemInboundQueueName: nahis_gp_system_inbound
    exchange: amq.direct
    username: ""
    password: ""
    maxAttempts: "3"
    backOffPeriod: "100"
