server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics
  health:
    mongo:
      enabled: false
nhais:
  amqp:
    brokers: ${NHAIS_AMQP_BROKERS}
    meshOutboundQueueName: ${NHAIS_MESH_OUTBOUND_QUEUE_NAME}
    exchange: amq.direct
    username: ${NHAIS_AMQP_USERNAME:}
    password: ${NHAIS_AMQP_PASSWORD:}
    maxAttempts: ${NHAIS_AMQP_MAX_RETRIES:3}
    backOffPeriod: ${NHAIS_AMQP_RETRY_DELAY:100}
  mongo:
    databaseName: ${NHAIS_MONGO_DATABASE_NAME:nhais}
    username: ${NHAIS_MONGO_USERNAME:}
    password: ${NHAIS_MONGO_PASSWORD:}
    host: ${NHAIS_MONGO_HOST:localhost}
    port: ${NHAIS_MONGO_PORT:27017}